### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by miguelgargallo** [chengsig/huntr-clone#28]
Starting the development server...

/Users/homer/Projs/1013/huntr-clone/node_modules/chokidar/lib/fsevents-handler.js:28
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/Users/homer/Projs/1013/huntr-clone/node_modules/chokidar/lib/fsevents-handler.js:28:11)
    at setFSEventsListener (/Users/homer/Projs/1013/huntr-clone/node_modules/chokidar/lib/fsevents-handler.js:82:16)
    at FsEventsHandler._watchWithFsEvents (/Users/homer/Projs/1013/huntr-clone/node_modules/chokidar/lib/fsevents-handler.js:252:16)
    at FSWatcher.<anonymous> (/Users/homer/Projs/1013/huntr-clone/node_modules/chokidar/lib/fsevents-handler.js:386:25)
    at LOOP (node:fs:2668:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by miguelgargallo** [comment]
Thanks for you time, and Merry Christmas 🎄
